export const content = {
  zh: {
    lang: 'zh-CN',
    title: '行间 Interline — 读懂世界，留在原文里',
    description:
      '行间是一款完全开源的 Chrome 双语阅读与翻译扩展。逐段对照原文、划词理解句子、原地翻译草稿。免 Key 开始，也可自备 AI 密钥。',
    skip: '跳到正文',
    nav: ['阅读体验', '翻译引擎', '常见问题'],
    install: '添加至 Chrome',
    source: '查看源代码',
    language: 'English',
    alternate: 'en/',
    eyebrow: 'INTERLINE · 开源双语阅读扩展',
    headline: '读懂世界，<br><span>留在原文里。</span>',
    intro: '让译文跟随阅读，让表达跨越语言。<br>从一篇文章到一句回复，在你原本的页面里完成。',
    note: '免费开源 · 无需注册 · Chrome 116+',
    explore: '看看行间如何工作',
    strip: ['原文与译文，逐段相伴', '免 Key 即可开始', '你的模型，由你选择'],
    experienceLabel: '01 / 阅读 · 理解 · 表达',
    experienceTitle: '让语言，少一点距离。',
    experienceIntro: '顺着你的阅读节奏，从读懂一页，到写下一句。',
    tabs: [
      {
        label: '双语阅读',
        title: '看见译文，也看见原意。',
        text: '原文与译文逐段相邻，不必在两个窗口间来回切换。双语、仅译文、仅原文，按自己的习惯阅读。',
        key: 'Alt + T',
        hint: '在网页上开始翻译',
        image: 'screenshot-1-bilingual.png',
        alt: '行间实际界面：英文文章与中文译文逐段相邻显示',
      },
      {
        label: '划词理解',
        title: '不懂的那一句，随手弄明白。',
        text: '选中文字，打开翻译卡片，查看、复制或朗读译文。支持的 AI 引擎还能提供词汇释义。',
        key: '选中文字',
        hint: '点击出现的翻译图标',
        image: 'screenshot-2-selection.png',
        alt: '行间实际界面：选中文字后打开的划词翻译卡片',
      },
      {
        label: '原地表达',
        title: '用自己的语言想，用另一种语言说。',
        text: '在输入框里写好草稿，连按三次空格即可翻译。阅读和写作目标语言独立设置，也可以暂时撤销翻译。',
        key: 'Space × 3',
        hint: '在输入框里翻译草稿',
        image: 'screenshot-4-input-translation.png',
        alt: '行间实际界面：输入框里的中文草稿翻译为英文，并显示撤销入口',
      },
    ],
    screenshotNote: '真实扩展截图 · 示例内容用于演示',
    engineLabel: '02 / 自由选择',
    engineTitle: '从直接可用，<br>到随你定制。',
    engineText: '用内置引擎轻松开始；想进一步调整翻译，就接入自己的 AI 服务。',
    engineBasic: '开箱即用',
    engineBasicText: '内置 Google Translate，无需 API Key。打开文章，开始阅读。',
    engineAI: '带上你的 AI',
    engineAIText: '接入自备密钥，使用自定义提示词、翻译风格和术语表，让专业用语更符合你的习惯。',
    compatible: '也支持兼容 OpenAI / Anthropic 协议的服务；正确配置后，可连接 Ollama 等本地服务。',
    cost: '内置在线服务的可用性取决于网络。第三方 AI 服务可能收取 API 费用，翻译质量取决于模型与配置。',
    trustLabel: '03 / 开放，也透明',
    trustTitle: '你的阅读，你来掌握。',
    trust: [
      ['MIT 完全开源', '全部源代码公开。可以查看实现、自行构建、修改，也欢迎一起贡献。'],
      ['无需注册账号', '没有行为分析埋点或遥测。设置与 API Key 保存在本地浏览器。'],
      ['直连所选服务', '不运营翻译中转服务器。待翻译文本直接发送给你选择的服务商。'],
    ],
    privacy: '了解数据去向',
    faqLabel: '开始之前',
    faqTitle: '你可能想知道',
    faqs: [
      [
        '行间免费吗？',
        '行间的代码以 MIT 协议免费开放，内置 Google Translate 引擎无需 API Key。若使用自己的 AI 服务，服务商可能按用量收费。',
      ],
      [
        '安装后怎么开始？',
        '从 Chrome 应用商店安装后，打开一篇外语文章，使用悬浮翻译控件、右键菜单或 Alt+T 开始翻译。点击浏览器工具栏中的行间图标，可以选择阅读目标语言和引擎。',
      ],
      [
        '所有网页都可以翻译吗？',
        '支持 Chrome 116 及以上版本。chrome:// 等浏览器限制页面无法使用网页内翻译。网站排版和编辑器实现不同，兼容性可能有所差异；遇到问题欢迎通过 GitHub Issue 反馈。',
      ],
      [
        '网页内容会发送到哪里？',
        '翻译请求从浏览器直接发送到你选择的服务商；内置引擎的接收方是 Google。AI 功能可能按需发送页面标题、相邻文本与术语表条目等上下文。开启“通读全文”后，会额外发送页面前 8,000 个字符。服务商有各自的数据政策，详情见隐私说明。',
      ],
      [
        '可以调整译文的样式吗？',
        '可以。行间提供三种阅读视图、10 种译文样式，以及浅色、深色外观。还可以配置站点自动翻译规则，并导出或导入设置。注意：导出的设置 JSON 包含 API Key，请妥善保管。',
      ],
    ],
    closing: '下一篇好文章，<br>不必止步于语言。',
    closingText: '装好行间，打开你一直想读的那一页。',
    footerTag: '读懂世界，留在原文里。',
    footer: ['源代码', '反馈问题', '隐私说明'],
  },
  en: {
    lang: 'en',
    title: 'Interline — Read beyond language. Keep the original in sight.',
    description:
      'An open-source Chrome extension for bilingual reading, selection translation, and translating drafts in place. Start without an API key, or bring your own AI.',
    skip: 'Skip to content',
    nav: ['Experience', 'Translation engines', 'FAQ'],
    install: 'Add to Chrome',
    source: 'View source',
    language: '简体中文',
    alternate: '../',
    eyebrow: 'INTERLINE · OPEN-SOURCE BILINGUAL READING',
    headline: 'Read beyond language.<br><span>Keep the original.</span>',
    intro:
      'Translations that follow your reading. Words that travel further.<br>From an article to a reply, stay on the page you’re already on.',
    note: 'Free & open source · No account · Chrome 116+',
    explore: 'Explore Interline',
    strip: ['Original and translation, together', 'Start without an API key', 'Your choice of AI model'],
    experienceLabel: '01 / READ · UNDERSTAND · REPLY',
    experienceTitle: 'A little closer to understanding.',
    experienceIntro: 'Follow your curiosity, from reading a page to writing a reply.',
    tabs: [
      {
        label: 'Read bilingually',
        title: 'See the translation. Keep the meaning in sight.',
        text: 'Read the original and translation side by side, paragraph by paragraph. Switch between bilingual, translation-only, and original-only views.',
        key: 'Alt + T',
        hint: 'Start translating a webpage',
        image: 'screenshot-1-bilingual.png',
        alt: 'Actual Interline interface with French paragraphs and their English translations',
      },
      {
        label: 'Understand a sentence',
        title: 'Make sense of the sentence that stops you.',
        text: 'Select text to read, copy, or listen to a translation. Supported AI engines can also provide vocabulary notes.',
        key: 'Select text',
        hint: 'Click the translation icon',
        image: 'screenshot-2-selection.png',
        alt: 'Actual Interline selection translation card on a webpage',
      },
      {
        label: 'Write in place',
        title: 'Think in your language. Reply in another.',
        text: 'Write a draft, then press Space three times to translate it in place. Set separate reading and writing languages, with a temporary undo option.',
        key: 'Space × 3',
        hint: 'Translate a draft in an input field',
        image: 'screenshot-4-input-translation.png',
        alt: 'Actual Interline input translation with the translated draft and undo control',
      },
    ],
    screenshotNote: 'Actual extension screenshots · Sample content for demonstration',
    engineLabel: '02 / YOUR CHOICE',
    engineTitle: 'Ready to read.<br>Room to make it yours.',
    engineText: 'Start with the built-in engine. Connect your own AI service when you want more control.',
    engineBasic: 'Ready out of the box',
    engineBasicText: 'Built-in Google Translate needs no API key. Open an article and start reading.',
    engineAI: 'Bring your own AI',
    engineAIText:
      'Connect your API key and customize prompts, translation styles, and glossaries for the words you work with.',
    compatible:
      'Also supports OpenAI / Anthropic-compatible services, including local services such as Ollama when configured appropriately.',
    cost: 'Built-in online translation depends on network and provider availability. AI providers may charge API fees. Quality depends on your model and configuration.',
    trustLabel: '03 / OPEN & TRANSPARENT',
    trustTitle: 'Your reading. In your hands.',
    trust: [
      ['MIT licensed. Fully open.', 'Inspect the source, build it yourself, adapt it, or contribute an improvement.'],
      [
        'No account needed',
        'No behavioral analytics or telemetry. Settings and API keys stay in your local browser storage.',
      ],
      [
        'Direct to your provider',
        'No Interline translation relay server. Text goes directly to the translation provider you choose.',
      ],
    ],
    privacy: 'See how data is handled',
    faqLabel: 'BEFORE YOU BEGIN',
    faqTitle: 'A few things to know',
    faqs: [
      [
        'Is Interline free?',
        'Interline’s code is free under the MIT license. Built-in Google Translate needs no API key. If you connect an AI service, your provider may charge for API usage.',
      ],
      [
        'How do I get started?',
        'Install from the Chrome Web Store, open an article, then use the floating translation control, right-click menu, or Alt+T. Click Interline in your browser toolbar to choose your reading language and engine.',
      ],
      [
        'Does it work on every webpage?',
        'Interline supports Chrome 116 and later. Restricted pages such as chrome:// cannot use in-page translation. Site layouts and editors vary, so compatibility is not guaranteed everywhere. Please report issues on GitHub.',
      ],
      [
        'Where does my page content go?',
        'Translation requests go directly from your browser to your chosen provider, including Google for the built-in engine. AI features may include the page title, nearby text, and glossary entries as context. Enabling whole-page context also sends the first 8,000 characters of page text. Providers have their own data policies; see the privacy policy for details.',
      ],
      [
        'Can I change how translations look?',
        'Yes. Choose from three reading views, 10 translation styles, and light or dark appearance. You can also set automatic translation rules per site and export or import settings. Exported settings JSON includes API keys, so keep it private.',
      ],
    ],
    closing: 'Your next great read.<br>A little less out of reach.',
    closingText: 'Install Interline. Open the page you’ve been meaning to read.',
    footerTag: 'Read beyond language. Keep the original in sight.',
    footer: ['Source code', 'Report an issue', 'Privacy policy'],
  },
};
